WebApplication/WebApplication/Areas/User/Models/UserViewModel.cs
namespace WebApplication.Models
{
    public class UserViewModel
    {
        public int Id { get; set; }

        public string UserName { get; set; }

        public string Email { get; set; }
    }
}

WebApplication/WebApplication/Models/StudentsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication.Models
{
    public enum Sex
    {
        Masculin = 1,
        Feminin=2
    }

    
    public class StudentsViewModel
    {
        public int ID { get; set; }
        [Display(Name = "Nume")]
        public string Nume { get; set; }
        [Display(Name = "Prenume")]
        public string Prenume { get; set; }
        [Display(Name = "Data Nasterii")]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DataNasterii { get; set; }
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string Email { get; set; }
        [Display(Name = "Telefon")]
        public string Telefon { get; set; }
        public Sex Sex { get; set; }
        [Display(Name = "Adresa")]
        public string Adresa { get; set; }
        [Display(Name = "Oras")]
        public string Oras { get; set; }
        [Display(Name ="Cod Postal")]
        public uint CodPostal { get; set; }
        [Display(Name ="Judet")]
        public string Judet { get; set; }
        public const string Tara = "Romania";
        public List<string> Hobbys = new List<string>();

    }
}

WebApplication/WebApplication/Areas/User/Controllers/UserController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class UserController : Controller
    {
        private static readonly List<UserViewModel> users = new List<UserViewModel>
        {
            new UserViewModel { Id = 1, Email = "dan@yahoo.com", UserName = "dan" },
            new UserViewModel { Id = 2, Email = "andrei@yahoo.com", UserName = "andrei" },
            new UserViewModel { Id = 3, Email = "vlad@yahoo.com", UserName = "vlad" },
        }; 

        [HttpGet]
        public ActionResult Index()
        {
            return View(users);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var model = users.Where(x => x.Id == id).FirstOrDefault();

            return View(model);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddNew()
        {
            var username = Request.Form["username"];
            var email = Request.Form["email"];

            var user = new UserViewModel { Email = email, UserName = username, Id = users.Count + 1 };

            users.Add(user);

            return RedirectToAction("Index");
        }
    }
}

WebApplication/WebApplication/Controllers/HomeController.cs
using System.Web.Mvc;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            // simulate go to database
            var model = new UserViewModel() { Email = "andrei@yahoo.com", UserName = "andrei"  };

            return View(model);
        }
    }
}

WebApplication/WebApplication/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class StudentController : Controller
    {
        private static readonly List<StudentsViewModel> students = new List<StudentsViewModel>
        {
            new StudentsViewModel {ID=1, Nume="Ionescu",Prenume="Ana",DataNasterii=new DateTime(2001, 12, 25),Email="ionescu_ana@yahoo.com",Sex=Sex.Feminin,Telefon="0741669147",Adresa="",Judet="Iasi",Oras="Iasi",CodPostal=89912 },
            new StudentsViewModel {ID=2, Nume="Popescu",Prenume="Ion",DataNasterii=new DateTime(1993, 10, 25),Email="ionescu_ana@yahoo.com",Sex=Sex.Feminin,Telefon="0741669147",Adresa="",Judet="Iasi",Oras="Iasi",CodPostal=89912 },
            new StudentsViewModel {ID=3, Nume="Vasilescu",Prenume="Gica",DataNasterii=new DateTime(2000, 12, 15),Email="ionescu_ana@yahoo.com",Sex=Sex.Feminin,Telefon="0741669147",Adresa="",Judet="Iasi",Oras="Iasi",CodPostal=89912 },
        };
        // GET: Student
        public ActionResult Index()
        {
            int s=students.Count();
            return View(s);
        }

        [HttpGet]
        public ActionResult Add ()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddStudent()

        {

            var student = new StudentsViewModel();
            student.Nume = Request["Last_Name"]; //aici pun numele inputului
            student.Prenume = Request["First_Name"];
            student.Adresa = Request["Address"];
            student.Email = Request["emailaddress"];
            student.Telefon = Request["Mobile_Number"];
            student.Oras = Request["City"];
            student.Judet = Request["State"];
            //student.Sex = Request["Gender"];
            var zi =Request["Birthday_day"];
            var luna = Request["Birthday_Month"];
            var an = Request["Birthday_Year"];
            student.ID = students.Count + 1;
            StringBuilder sb = new StringBuilder();
            sb.Append(zi+"/"+ luna+"/"+an);
            student.DataNasterii = Convert.ToDateTime(sb);
            students.Add(student);
            
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult ViewStudents()
        {
            return View(students);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var model = students.Where(x => x.ID == id).FirstOrDefault();

            return View(model);
        }

        [HttpGet]
        public ActionResult Edit()
        {
            var id = Request.QueryString["id"];
            return View();
        }

        [HttpPost]
        public ActionResult Edit (int id)
        {
            var s = students.Where(x => x.ID == id).FirstOrDefault();
            //if (Request[])
            //    student.Nume = Request["Last_Name"]; //aici pun numele inputului
            //student.Prenume = Request["First_Name"];
            //student.Adresa = Request["Address"];
            //student.Email = Request["emailaddress"];
            //student.Telefon = Request["Mobile_Number"];
            //student.Oras = Request["City"];
            //student.Judet = Request["State"];
            ////student.Sex = Request["Gender"];
            //var zi = Request["Birthday_day"];
            //var luna = Request["Birthday_Month"];
            //var an = Request["Birthday_Year"];
            //student.ID = students.Count + 1;
            //StringBuilder sb = new StringBuilder();
            //sb.Append(zi + "/" + luna + "/" + an);
            //student.DataNasterii = Convert.ToDateTime(sb);
            //students.Add(student);

            return RedirectToAction("Index");
        }
        
    }
}

WebApplication/WebApplication/Areas/User/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Students&Users", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Users", "Index", "User")</li>
                    <li>@Html.ActionLink("Students", "Index", "Student")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication/WebApplication/Areas/User/Views/User/Add.cshtml
@model WebApplication.Models.UserViewModel

@{
    ViewBag.Title = "Add new user";
}

<h2>Add new user</h2>

<div>
    <form method="post" action="/user/addnew">
        <div class="form-group">
            <label for="usr">Email:</label>
            <input name="email" type="email" class="form-control" id="usr">
        </div>
        <div class="form-group">
            <label for="pwd">UserName:</label>
            <input name="username" type="text" class="form-control" id="pwd">
        </div>
        <input type="submit"/>
    </form>
</div>

WebApplication/WebApplication/Areas/User/Views/User/Details.cshtml
@model WebApplication.Models.UserViewModel

@{
    ViewBag.Title = "User Details";
}

<h2>User details</h2>

<div>
    <h4>@Model.Id</h4>
    <h4>@Model.Email</h4>
    <h4>@Model.UserName</h4>
</div>

WebApplication/WebApplication/Areas/User/Views/User/Index.cshtml
@model List<WebApplication.Models.UserViewModel>

@{
    ViewBag.Title = "Users";
}

<h2>Users</h2>

<div>
    <table class="table">
        <thead>
            <tr>
                <td>Id</td>
                <td>Email</td>
                <td>UserName</td>
                <td>Details</td>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var user in Model)
                {   
                        <tr>
                            <td>@user.Id</td>
                            <td>@user.Email</td>
                            <td>@user.UserName</td>
                            <td><a href="/User/Details/@user.Id">Go</a></td>
                        </tr>
                }
            }
        </tbody>
    </table>
</div>

<div>
    @Html.ActionLink("Add user", "Add", "User")
</div>

WebApplication/WebApplication/Views/Home/Index.cshtml
@model WebApplication.Models.UserViewModel

@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Users&Students</h1>
    
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Users</h2>
        <p>
            Exemplul facut la curs, Add, details si Index.
        </p>
        <p><a class="btn btn-default" href="/User">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Students</h2>
        <p>Exemplele din tema - students - Add, Details, Edit, Index si ViewStudents</p>
        <p><a class="btn btn-default" href="/Student"> Learn more &raquo;</a></p>
    </div>
    
    <div class="col-md-12">
        <h2>User</h2>
        <div>@Model.Email</div>
        <div>@Model.UserName</div>
    </div>
</div>

WebApplication/WebApplication/Views/Student/Add.cshtml
@using WebApplication.Models

@section Scripts {

    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0"
            });

        });
    </script>

}
@model WebApplication.Models.StudentsViewModel

@{
    ViewBag.Title = "Add";
}
<head>
    <title>Student Registration Form</title>
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <h3>Formular inscriere Studenti</h3>

    <form method="get" action="www.google.com">
        <table align="center" cellpadding="10">

            <!----- First Name ---------------------------------------------------------->
            <tr>
                <td>Prenume</td>
                <td>
                    @Html.TextBox("Prenume", "Prenume Student", new { @class = "form-control" })
                    (max 30 caractere a-z/A-Z)
                </td>
            </tr>

            <!----- Last Name ---------------------------------------------------------->
            <tr>
                <td>Nume</td>
                <td>
                    @Html.TextBox("Nume", "Nume Student", new { @class = "form-control" })
                    (max 30 caractere a-z/A-Z)
                </td>
            </tr>

            <!----- Date Of Birth -------------------------------------------------------->
            <tr>
                <td>Data Nasterii</td>
                <td>
                    @Html.EditorFor(model => model.DataNasterii,
new { htmlAttributes = new { @class = "form-control date-picker" } })

                </td>

            </tr>

            <!----- Email Id ---------------------------------------------------------->
            <tr>
                <td>E-mail</td>
                <td>
                    @Html.Editor("Email") <br />
                    @Html.ValidationMessage("Email", "", new { @class = "email" })
                </td>
            </tr>

            <!----- Mobile Number ---------------------------------------------------------->
            <tr>
                <td>Telefon</td>
                <td>
                    @Html.Editor("Telefon") <br />
                    @Html.ValidationMessage("Telefon", "", new { @class = "tel" })
                </td>
            </tr>

            <!----- Gender ----------------------------------------------------------->
            <tr>
                <td>Sex</td>
                <td>
                    M @Html.RadioButtonFor(m => m.Sex, "Masculin")
                    F @Html.RadioButtonFor(m => m.Sex, "Feminin")
                </td>
            </tr>

            <!----- Address ---------------------------------------------------------->
            <tr>
                <td>Adresa <br /><br /><br /></td>
                <td>
                    @Html.TextArea("Adresa", "", new { @class = "form-control" })
                </td>

            </tr>

            <!----- City ---------------------------------------------------------->
            <tr>
                <td>Oras</td>
                <td>
                    @Html.TextBox("Oras", "", new { @class = "form-control" })
                    (max 30 caractere)
                </td>
            </tr>

            <!----- Pin Code ---------------------------------------------------------->
            <tr>
                <td>Cod Postal</td>
                <td>
                    @Html.TextBox("Cod Postal", "", new { @class = "form-control" })
                    (max 6 caractere)
                </td>
            </tr>

            <!----- State ---------------------------------------------------------->
            <tr>
                <td>Judet</td>
                <td>
                    @Html.TextBox("Judet", "", new { @class = "form-control" })
                </td>
            </tr>

            <!----- Country ---------------------------------------------------------->
            <tr>
                <td>Tara</td>
                <td><input type="text" name="Country" value="Romania" readonly="readonly" /></td>
            </tr>

            <!----- Hobbies ---------------------------------------------------------->

            <tr>
                <td>Hobby-uri <br /><br /><br /></td>

                <td>
                    Desenat
                    <input type="checkbox" name="Hobby_Drawing" value="Drawing" />
                    Cantat
                    <input type="checkbox" name="Hobby_Singing" value="Singing" />
                    Pescuit
                    <input type="checkbox" name="Hobby_Dancing" value="Dancing" />
                    Dans
                    <input type="checkbox" name="Hobby_Cooking" value="Cooking" />
                    <br />
                    Altele
                    <input type="checkbox" name="Hobby_Other" value="Other">
                    <input type="text" name="Other_Hobby" maxlength="30" />
                </td>
            </tr>

            <!----- Qualification---------------------------------------------------------->
            <tr>
                <td>Limbi Straine <br /><br /><br /><br /><br /><br /><br /></td>

                <td>
                    <table>

                        <tr>
                            <td align="center"><b>Nr. Criteriu</b></td>
                            <td align="center"><b>Limba staina</b></td>
                            <td align="center"><b>Vorbit</b></td>
                            <td align="center"><b>Scris</b></td>
                            <td align="center"><b>Citit</b></td>
                        </tr>

                        <tr>
                            <td>1</td>
                            <td>Engleza</td>
                            <td><input type="text" name="Engleza_Vorbit" maxlength="30" /></td>
                            <td><input type="text" name="Engleza_Scris" maxlength="30" /></td>
                            <td><input type="text" name="Engleza_Citit" maxlength="30" /></td>
                        </tr>

                        <tr>
                            <td>2</td>
                            <td>Franceza</td>
                            <td><input type="text" name="Franceza_Vorbit" maxlength="30" /></td>
                            <td><input type="text" name="Franceza_Scris" maxlength="30" /></td>
                            <td><input type="text" name="Franceza_Citit" maxlength="30" /></td>
                        </tr>

                        <tr>
                            <td>3</td>
                            <td>Germana</td>
                            <td><input type="text" name="Germana_Vorbit" maxlength="30" /></td>
                            <td><input type="text" name="Germana_Scris" maxlength="30" /></td>
                            <td><input type="text" name="Germana_Citit" maxlength="30" /></td>
                        </tr>

                        <tr>
                            <td>4</td>
                            <td>Spaniola</td>
                            <td><input type="text" name="Spaniola_Vorbit" maxlength="30" /></td>
                            <td><input type="text" name="Spaniola_Scris" maxlength="30" /></td>
                            <td><input type="text" name="Spaniola_Citit" maxlength="30" /></td>
                        </tr>


                    </table>

                </td>
            </tr>

            <!----- Submit and Reset ------------------------------------------------->
            <tr>
                <td colspan="2" align="center">
                    <button type="submit">Submit</button>
                    <button type="reset" value="Reset" action=clear>Reset</button>
                </td>
            </tr>
        </table>

    </form>

</body>

WebApplication/WebApplication/Views/Student/Details.cshtml
@model WebApplication.Models.StudentsViewModel

@{
    ViewBag.Title = "Details";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Details for: @Model.Nume @Model.Prenume</h4>
        <h3></h3>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nume)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Nume)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Prenume)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Prenume)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DataNasterii)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DataNasterii)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Telefon)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Telefon)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Adresa)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Adresa)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Oras)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Oras)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CodPostal)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CodPostal)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Judet)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Judet)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

WebApplication/WebApplication/Views/Student/Edit.cshtml
@model WebApplication.Models.StudentsViewModel

@{
    ViewBag.Title = "Edit Student Details";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>StudentsViewModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Nume, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nume, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nume, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Prenume, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Prenume, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Prenume, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DataNasterii, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DataNasterii, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DataNasterii, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Adresa, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Adresa, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Adresa, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Oras, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Oras, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Oras, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CodPostal, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CodPostal, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CodPostal, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Judet, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Judet, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Judet, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

WebApplication/WebApplication/Views/Student/Index.cshtml
@model Int32?

@{
    ViewBag.Title = "Students";
}

<h2>Students</h2>

<div>
     
    <fieldset>
        <legend>Total number of students is:</legend>
        <div>@Model</div>
    </fieldset>
</div>
<div>
    @Html.ActionLink("Add new student", "Add", "Student")
    @Html.ActionLink("View all students", "ViewStudents", "Student")
    

</div>

WebApplication/WebApplication/Views/Student/ViewStudents.cshtml
@model IEnumerable<WebApplication.Models.StudentsViewModel>

@{
    ViewBag.Title = "View";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View all students</title>
</head>
<body>
    <p>
        @Html.ActionLink("Add new student", "Add", "Student")
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Nume
                </th>
                <th>
                    Prenume
                </th>
                

            </tr>
        </thead>
        <tbody>
        @{ foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nume)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prenume)
                </td>

                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                <a href="/Student/Details/@item.ID">See details</a> |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })

                </td>
            </tr>
                }
            }

    </table>
</body>
</html>